name: Generate debug APK

on:
  push:
  workflow_dispatch:

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Node.js (use version 16 or latest LTS)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies (yarn install)
      - name: Install dependencies
        run: |
          yarn install --no-frozen-lockfile

      # Update Expo modules to the latest version
      - name: Update Expo dependencies
        run: |
          yarn upgrade expo@latest
          yarn upgrade expo-media-library@latest

      # Set up JDK 17 (to match Android Gradle plugin requirement)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Clean the project (remove node_modules and android/build)
      - name: Clean project
        run: |
          rm -rf node_modules
          rm -rf android/build
          yarn install --no-frozen-lockfile  # Reinstall dependencies

      # Grant execute permissions to gradlew
      - name: Grant execute permissions to gradlew
        run: chmod +x ./android/gradlew

      # Navigate to Android directory and clean build
      - name: Navigate to Android directory and clean build
        run: |
          cd ./android
          ls -l  # Check if gradlew is in the correct directory
          ./gradlew clean

      # Build debug APK
      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug --stacktrace 

      # Rename APK for output
      - name: Rename APK 
        run:
          mv "./app/build/outputs/apk/debug/app-debug.apk" "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"

      # Upload the APK as an artifact
      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk
